import Preferences: @load_preference, @set_preferences!, load_preference
if @load_preference("distributed-package") == "DistributedNext"
    using DistributedNext
else
    using Distributed
end

import Profile
import Base.gc_num

export timespan_start, timespan_finish, @logstart, @logfinish, @logcategory

const Timestamp = UInt64

struct ProfilerResult
    samples::Vector{UInt}
    lineinfo::AbstractDict
    tasks::Vector{UInt}
end
ProfilerResult(samples, lineinfo, tasks::Vector{Task}) =
    ProfilerResult(samples, lineinfo, map(Base.pointer_from_objref, tasks))
ProfilerResult(samples, lineinfo, tasks::Nothing) =
    ProfilerResult(samples, lineinfo, UInt[])

const EMPTY_PROF = ProfilerResult(UInt[], Dict{UInt64, Vector{Base.StackTraces.StackFrame}}(), UInt[])
empty_prof() = EMPTY_PROF

"""
    set_distributed_package!(value[="Distributed|DistributedNext"])

Set a [preference](https://github.com/JuliaPackaging/Preferences.jl) for using
either the Distributed.jl stdlib or DistributedNext.jl. You will need to restart
Julia after setting a new preference.
"""
function set_distributed_package!(value)
    @set_preferences!("distributed-package" => value)
    @info "TimespanLogging.jl preference has been set, restart your Julia session for this change to take effect!"
end

"""
    Timespan

Identifies space (category, id) and time (timeline, start, finish). It also
tracks GC allocations and profiling samples.
"""
struct Timespan
    category::Symbol
    id::Any
    timeline::Any
    start::Timestamp
    finish::Timestamp
    gc_diff::Base.GC_Diff
    profiler_samples::ProfilerResult
end

"An event generated by `timespan_start` or `timespan_finish`."
struct Event{phase}
    category::Symbol
    id::Any
    timeline::Any
    timestamp::Timestamp
    gc_num::Base.GC_Num
    profiler_samples::ProfilerResult
end

@inline Event(phase::Symbol, category::Symbol,
              @nospecialize(id), @nospecialize(tl),
              time, gc_num, prof) =
    Event{phase}(category, id, tl, time, gc_num, prof)

"""
    make_timespan(start::Event, finish::Event) -> Timespan
"""
function make_timespan(start::Event, finish::Event)
    @assert start.category == finish.category
    @assert start.id == finish.id

    Timespan(start.category,
             start.id,
             finish.timeline,
             start.timestamp,
             finish.timestamp,
             Base.GC_Diff(finish.gc_num, start.gc_num),
             mix_samples(start.profiler_samples, finish.profiler_samples))
end

"""
    NoOpLog

Disables event logging entirely.
"""
struct NoOpLog end

"""
    ActiveLog

Token sink used by `enable_logging!`. Events are recorded into per-thread
chunk lists and consumed at `get_logs!`.
"""
struct ActiveLog end

"""
    get_logs!(ctx; kwargs...)
    get_logs!(sink; kwargs...)

Get the logs recorded by `ctx`'s (or `sink`'s) log sink, clearing them in the
process. Recording is always into per-thread buffers regardless of sink;
`get_logs!` is what steals and projects them into the sink's own log shape
(a `Vector{Timespan}` for `LocalEventLog`, a `Dict` of consumer name to
per-event values for `MultiEventLog`, `nothing` for `NoOpLog`). See the
sink's own docstring for sink-specific keyword arguments (e.g. `raw` and
`only_local` on `LocalEventLog`).
"""
get_logs!(ctx; kwargs...) = get_logs!(log_sink(ctx); kwargs...)
write_event(::NoOpLog, event::Event) = nothing
get_logs!(::NoOpLog) = nothing
