.gputest: &gputest
  timeout_in_minutes: 60
  if: build.message !~ /\[skip tests\]/

steps:
  - label: Julia 1.11 (CUDA)
    <<: *gputest
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "cuda"
    env:
      CI_USE_CUDA: "1"

  - label: Julia 1.11 (ROCm)
    <<: *gputest
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "rocm"
    env:
      CI_USE_ROCM: "1"

  - label: Julia 1.11 (oneAPI)
    <<: *gputest
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "oneapi"
    env:
      CI_USE_ONEAPI: "1"

  - label: Julia 1.11 (Metal)
    timeout_in_minutes: 20
    <<: *gputest
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "metal"
    env:
      CI_USE_METAL: "1"

# env:
#   SECRET_CODECOV_TOKEN: ""
