.test: &test
  if: build.env("DAGGER_BENCHMARK") != "true"
  agents:
    os: linux
    arch: x86_64
  plugins:
    - docker#v3.7.0:
        image: julia:1
steps:
  - label: Julia 1.x
    command: julia --project -e 'using Pkg; Pkg.build(); Pkg.test()'
    timeout_in_minutes: 60
    <<: *test
  - label: Julia nightly
    command: |
      mkdir /tmp/julia
      curl https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz | tar -C /tmp/julia --strip-components=1 -zxf -
      /tmp/julia/bin/julia --project -e 'using InteractiveUtils; versioninfo()'
      /tmp/julia/bin/julia --project -e 'using Pkg; Pkg.build(); Pkg.test()'
    timeout_in_minutes: 60
    <<: *test
  - label: Benchmarks
    command: echo TODO
    if: build.env("DAGGER_BENCHMARK") == "true"
    agents:
      os: linux
      arch: x86_64
      serial: true
    plugins:
      - docker#v3.7.0:
          image: julia:1.5.3
    artifacts:
      - benchmarks/TODO
