.test: &test
  if: build.env("DAGGER_BENCHMARK") != "true"
  agents:
    queue: "juliaecosystem"
    sandbox.jl: "true"
steps:
  - label: Julia 1.7
    timeout_in_minutes: 60
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
  - label: Julia nightly
    timeout_in_minutes: 60
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7-nightly"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      # - JuliaCI/julia-coverage#v1:
      #     codecov: true
  - label: Benchmarks
    command: echo TODO
    if: build.env("DAGGER_BENCHMARK") == "true"
    agents:
      os: linux
      arch: x86_64
      serial: true
    plugins:
      - docker#v3.7.0:
          image: julia:1.7.0
    artifacts:
      - benchmarks/TODO
