.test: &test
  if: build.message !~ /\[skip tests\]/
  agents:
    queue: "juliaecosystem"
    sandbox_capable: "true"
    os: linux
    arch: x86_64
  command: "julia --project -e 'using Pkg; Pkg.develop(;path=\"lib/TimespanLogging\"); Pkg.add(; url=\"https://github.com/JuliaData/MemPool.jl\", rev=\"jps/migration-helper\")'"

.bench: &bench
  if: build.message =~ /\[run benchmarks\]/
  agents:
    queue: "juliaecosystem"
    sandbox_capable: "true"
    os: linux
    arch: x86_64
    num_cpus: 16

steps:
  - label: Julia 1.9
    timeout_in_minutes: 90
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      - JuliaCI/julia-coverage#v1:
          codecov: true

  - label: Julia 1.10
    timeout_in_minutes: 90
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      - JuliaCI/julia-coverage#v1:
          codecov: true

  - label: Julia nightly
    timeout_in_minutes: 90
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10-nightly"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
  - label: Julia 1.9 (macOS)
    timeout_in_minutes: 90
    <<: *test
    agents:
      queue: "juliaecosystem"
      os: macos
      arch: x86_64
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9"
      - JuliaCI/julia-test#v1:
          julia_args: "--threads=1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
  - label: Julia 1.9 - TimespanLogging
    timeout_in_minutes: 20
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: "julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.develop(;path=\"lib/TimespanLogging\"); Pkg.test(\"TimespanLogging\")'"
  - label: Julia 1.9 - DaggerWebDash
    timeout_in_minutes: 20
    <<: *test
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: "julia -e 'using Pkg; Pkg.develop(;path=pwd()); Pkg.develop(;path=\"lib/TimespanLogging\"); Pkg.develop(;path=\"lib/DaggerWebDash\"); include(\"lib/DaggerWebDash/test/runtests.jl\")'"

  - label: Benchmarks
    timeout_in_minutes: 120
    <<: *bench
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9"
      - JuliaCI/julia-test#v1:
          run_tests: false
    command: "julia -e 'using Pkg; Pkg.add(\"BenchmarkTools\"); Pkg.develop(;path=pwd())'; JULIA_PROJECT=\"$PWD\" julia --project benchmarks/benchmark.jl"
    env:
      JULIA_NUM_THREADS: "4"
      BENCHMARK: "nmf:raw,dagger"
      BENCHMARK_PROCS: "4:4"
      BENCHMARK_SCALE: "5:5:50"
    artifacts:
      - benchmarks/result*

  - label: DTables.jl stability test
    timeout_in_minutes: 20
    plugins:
      - JuliaCI/julia#v1:
          version: "1.9"
    env:
      JULIA_NUM_THREADS: "4"
    agents:
      queue: "juliaecosystem"
      sandbox_capable: "true"
      os: linux
      arch: x86_64
    command: "git clone https://github.com/JuliaParallel/DTables.jl.git ; julia -t4 -e 'using Pkg; Pkg.activate(\"DTables.jl\"); Pkg.develop(;path=\".\"); Pkg.instantiate(); Pkg.test()'"
