"""
    tochunk(x, proc::Processor, space::MemorySpace, scope::AbstractScope=AnyScope(); device=nothing, type=typeof(x), rewrap=false, kwargs...) -> Chunk

Create a chunk from data `x` which resides on `proc`, lives in memory space
`space`, and has scope `scope`.

`proc` and/or `space` may be omitted, in which case they are derived from the
current acceleration (via `default_processor`/`default_memory_space`); `scope`
defaults to `AnyScope()`. The one-argument form `tochunk(x)` derives all three,
so that (for example) under `MPIAcceleration` the resulting `Chunk` gets an
`MPIRef` handle and `MPIMemorySpace`, rather than a rank-local `DRef` and
`CPURAMMemorySpace`.

`space` determines how the data is stored: `tochunk_pset(x, space; ...)` builds
the appropriate handle for that space (e.g. a `DRef` for `CPURAMMemorySpace`, an
`MPIRef` under MPI). It is also recorded on the `Chunk` for aliasing and
data-movement decisions.

`device` specifies a `MemPool.StorageDevice` (which is itself wrapped in a
`Chunk`) which will be used to manage the reference contained in the `Chunk`
generated by this function. If `device` is `nothing` (the default), the data
will be inspected to determine if it's safe to serialize; if so, the default
MemPool storage device will be used; if not, then a `MemPool.CPURAMDevice` will
be used.

`type` can be specified manually to force the type to be `Chunk{type}`. A
placeholder chunk for remote data (`x === nothing`) must pass an explicit,
non-`Nothing` `type`.

If `rewrap==true` and `x isa Chunk`, then the `Chunk` will be rewrapped in a
new `Chunk`.

All other kwargs are passed directly to `MemPool.poolset`.
"""
tochunk(x::X, proc::P, space::M; kwargs...) where {X,P<:Processor,M<:MemorySpace} =
    tochunk(x, proc, space, AnyScope(); kwargs...)
function tochunk(x::X, proc::P, space::M, scope::S; device=nothing, type=X, rewrap=false, kwargs...) where {X,P<:Processor,S,M<:MemorySpace}
    if type === Nothing && x !== nothing
        # Placeholders for remote data must carry an explicit element type
        throw(ArgumentError("Chunk type cannot be Nothing. Placeholder chunks must be created with an explicit type= (e.g. tochunk(nothing, proc, space; type=Matrix{Float64})). x=$(repr(x))"))
    end
    if x isa Chunk
        check_proc_space(x, proc, space)
        return maybe_rewrap(x, proc, space, scope; type, rewrap)
    end
    if device === nothing
        device = if Sch.walk_storage_safe(x)
            MemPool.GLOBAL_DEVICE[]
        else
            MemPool.CPURAMDevice()
        end
    end
    ref = tochunk_pset(x, space; device, type, kwargs...)
    return Chunk{type,typeof(ref),P,S,typeof(space)}(type, domain(x), ref, proc, scope, space)
end
# Disambiguate: Chunk-specific 3-arg so kwcall(tochunk, Chunk, Processor, Scope) is not ambiguous with utils/chunks.jl
function tochunk(x::Chunk, proc::P, scope::S; rewrap=false, kwargs...) where {P<:Processor,S}
    if rewrap
        return remotecall_fetch(x.handle.owner) do
            tochunk(MemPool.poolget(x.handle), proc, scope; kwargs...)
        end
    else
        return x
    end
end
function tochunk(x::X, proc::P, scope::S; device=nothing, type=X, rewrap=false, kwargs...) where {X,P<:Processor,S}
    if type === Nothing && x !== nothing
        # Placeholders for remote data must carry an explicit element type
        throw(ArgumentError("Chunk type cannot be Nothing. Placeholder chunks must be created with an explicit type= (e.g. tochunk(nothing, proc, space; type=Matrix{Float64})). x=$(repr(x))"))
    end
    if device === nothing
        device = if Sch.walk_storage_safe(x)
            MemPool.GLOBAL_DEVICE[]
        else
            MemPool.CPURAMDevice()
        end
    end
    if x isa Chunk
        space = x.space
        check_proc_space(x, proc, space)
        return maybe_rewrap(x, proc, space, scope; type, rewrap)
    end
    space = default_memory_space(current_acceleration(), x)
    ref = tochunk_pset(x, space; device, type, kwargs...)
    return Chunk{type,typeof(ref),P,S,typeof(space)}(type, domain(x), ref, proc, scope, space)
end
function tochunk(x::X, space::M, scope::S; device=nothing, type=X, rewrap=false, kwargs...) where {X,M<:MemorySpace,S}
    if type === Nothing && x !== nothing
        # Placeholders for remote data must carry an explicit element type
        throw(ArgumentError("Chunk type cannot be Nothing. Placeholder chunks must be created with an explicit type= (e.g. tochunk(nothing, proc, space; type=Matrix{Float64})). x=$(repr(x))"))
    end
    if device === nothing
        device = if Sch.walk_storage_safe(x)
            MemPool.GLOBAL_DEVICE[]
        else
            MemPool.CPURAMDevice()
        end
    end
    if x isa Chunk
        proc = x.processor
        check_proc_space(x, proc, space)
        return maybe_rewrap(x, proc, space, scope; type, rewrap)
    end
    proc = default_processor(current_acceleration(), x)
    ref = tochunk_pset(x, space; device, type, kwargs...)
    return Chunk{type,typeof(ref),typeof(proc),S,M}(type, domain(x), ref, proc, scope, space)
end
# 2-arg: avoid overwriting utils/chunks.jl's tochunk(Any, Any) and tochunk(Any); only add Processor/MemorySpace variants
# Chunk + Processor: disambiguate vs utils/chunks.jl's tochunk(x::Chunk, proc; ...)
tochunk(x::Chunk, proc::Processor; kwargs...) = tochunk(x, proc, AnyScope(); kwargs...)
tochunk(x, proc::Processor; kwargs...) = tochunk(x, proc, AnyScope(); kwargs...)
tochunk(x, space::MemorySpace; kwargs...) = tochunk(x, space, AnyScope(); kwargs...)

# 1-arg: route through the current acceleration so the resulting Chunk gets
# the appropriate handle and memory space (e.g. MPIRef + MPIMemorySpace under
# MPIAcceleration, instead of a rank-local DRef + CPURAMMemorySpace).
# N.B. This overrides the default-argument method generated by
# utils/chunks.jl's `tochunk(x, proc=OSProc(), scope=AnyScope())`.
function tochunk(x)
    accel = current_acceleration()
    return tochunk(x, default_processor(accel, x), default_memory_space(accel, x), AnyScope())
end

check_proc_space(x, proc, space) = nothing
function check_proc_space(x::Chunk, proc, space)
    if x.space !== space
        throw(ArgumentError("Memory space mismatch: Chunk=$(x.space) != Requested=$space"))
    end
end
function check_proc_space(x::Thunk, proc, space)
    # FIXME: Validate
end
function maybe_rewrap(x, proc, space, scope; type, rewrap)
    if rewrap
        return remotecall_fetch(x.handle.owner) do
            tochunk(MemPool.poolget(x.handle), proc, scope; kwargs...)
        end
    else
        return x
    end
end

tochunk_pset(x, space::MemorySpace; device=nothing, type=nothing, kwargs...) = poolset(x; device, kwargs...)

# savechunk: defined in utils/chunks.jl (fork Chunk has space field; do not duplicate here)
